name: "SchemaShield CI"
description: "Prevent LLM output drift by validating prompts against JSON schemas in your CI pipeline"
author: "SchemaShield"
branding:
  icon: shield
  color: blue
inputs:
  token:
    description: "SchemaShield project API key (starts with ssk_). Get yours at https://schemashield.ai"
    required: true
  provider:
    description: "LLM provider (e.g., openai, anthropic)"
    required: true
    default: "openai"
  model:
    description: "Model name to test against (e.g., gpt-4o-mini, claude-3-5-sonnet)"
    required: true
  schemas:
    description: "Path to directory containing JSON schema files (.json)"
    required: true
  prompts:
    description: "Path to directory containing prompt files (matched to schemas by filename)"
    required: true
  seeds:
    description: "Number of test variations to run per prompt (higher = more thorough)"
    required: false
    default: "1"
  mode:
    description: "Validation mode: 'validate' (fast check) or 'repair' (attempt fixes)"
    required: false
    default: "validate"
  api_url:
    description: "SchemaShield API base URL (advanced usage only)"
    required: false
    default: "https://schemashield.ai"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Run CI
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_SCHEMAS_DIR: ${{ inputs.schemas }}
        INPUT_PROMPTS_DIR: ${{ inputs.prompts }}
        INPUT_SEEDS: ${{ inputs.seeds }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_API_URL: ${{ inputs.api_url }}
      run: |
        node ci.js
